import { build } from "esbuild";
import { fileURLToPath } from "node:url";

const packageDir = fileURLToPath(new URL("..", import.meta.url));
const outfile = fileURLToPath(
  new URL("../../../actions/dependency-cooldown/dist/index.mjs", import.meta.url),
);

await build({
  entryPoints: [`${packageDir}src/cli.ts`],
  outfile,
  bundle: true,
  platform: "node",
  target: "node20",
  format: "esm",
  // Resolve dependencies to their ESM builds. Their CommonJS/UMD builds use
  // dynamic relative require() calls that cannot survive bundling.
  mainFields: ["module", "main"],
  conditions: ["import", "node"],
  minify: false,
  sourcemap: false,
  legalComments: "none",
  banner: {
    js: [
      "// Generated by packages/dependency-cooldown; run `npm run build` after changing src/.",
      // `yaml` only ships a CommonJS build for Node and calls require()
      // internally. esbuild's require shim uses this binding when it exists.
      'import { createRequire as __nodeCreateRequire } from "node:module";',
      "const require = __nodeCreateRequire(import.meta.url);",
    ].join("\n"),
  },
});

console.log(`Bundled ${outfile}`);
